name: Build ReVanced

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Setup JDK
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: zulu

      - name: Download ReVanced CLI
        uses: robinraju/release-downloader@v1.12
        with:
          repository: 'ReVanced/revanced-cli'
          latest: true
          fileName: '*.jar'

      - name: Download ReVanced Patches
        uses: robinraju/release-downloader@v1.12
        with:
          repository: 'ReVanced/revanced-patches'
          latest: true
          fileName: '*.rvp'

      - name: Download YouTube APK
        uses: robinraju/release-downloader@v1.12
        with:
          repository: '${{ github.repository }}'
          tag: base
          fileName: yt.apk

      - name: Build APKs
        run: ./scripts/build.sh -r

      - name: Set current date as env variable
        run: >-
          echo "date_now=$(date +'%Y-%m-%d')" >> $GITHUB_ENV && echo
          "date_now_nodashes=$(date +'%Y%m%d')" >> $GITHUB_ENV

      - uses: kevin-david/zipalign-sign-android-release@v2.0.2
        name: Sign ReVanced APK
        id: sign_yt
        with:
          releaseDirectory: build/yt/
          signingKeyBase64: '${{ secrets.SIGNING_KEY }}'
          alias: '${{ secrets.ALIAS }}'
          keyStorePassword: '${{ secrets.KEY_STORE_PASSWORD }}'
          keyPassword: '${{ secrets.KEY_PASSWORD }}'

      - name: Generate SHA256 checksums for the signed APK file
        run: ./scripts/sha256gen.sh -r

      - uses: marvinpinto/action-automatic-releases@latest
        name: Release ReVanced
        with:
          repo_token: '${{ secrets.GITHUB_TOKEN }}'
          automatic_release_tag: '${{ env.date_now_nodashes }}-yt'
          title: 'ReVanced ${{ env.date_now }}'
          prerelease: false
          files: |
            build/hashes/sha256-yt.txt
            ${{ steps.sign_yt.outputs.signedReleaseFile }}
