name: Build YouTube Music

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Setup JDK
        uses: actions/setup-java@v5
        with:
          java-version: '25'
          distribution: zulu

      - name: Download Morphe CLI
        uses: robinraju/release-downloader@v1.13
        with:
          repository: 'MorpheApp/morphe-cli'
          latest: true
          fileName: '*.jar'

      - name: Download Morphe patches
        uses: robinraju/release-downloader@v1.13
        with:
          repository: 'MorpheApp/morphe-patches'
          latest: true
          fileName: '*.mpp'

      - name: Download YouTube Music APKs
        uses: robinraju/release-downloader@v1.13
        with:
          repository: '${{ github.repository }}'
          tag: base
          fileName: music*.apk

      - name: Build APKs
        run: ./scripts/build.sh -m

      - name: Set current date as env variable
        run: >-
          echo "date_now=$(date +'%Y-%m-%d')" >> $GITHUB_ENV && echo
          "date_now_nodashes=$(date +'%Y%m%d')" >> $GITHUB_ENV

      - uses: kevin-david/zipalign-sign-android-release@v2.0.2
        name: Sign YouTube Music APKs
        id: sign_ytm
        with:
          releaseDirectory: build/ytm/
          signingKeyBase64: '${{ secrets.SIGNING_KEY }}'
          alias: '${{ secrets.ALIAS }}'
          keyStorePassword: '${{ secrets.KEY_STORE_PASSWORD }}'
          keyPassword: '${{ secrets.KEY_PASSWORD }}'

      - name: Generate SHA256 checksums for the signed APK files
        run: ./scripts/sha256gen.sh -m

      - uses: marvinpinto/action-automatic-releases@latest
        name: Release YouTube Music
        with:
          repo_token: '${{ secrets.GITHUB_TOKEN }}'
          automatic_release_tag: '${{ env.date_now_nodashes }}-ytm'
          title: 'Morphe YTM ${{ env.date_now }}'
          prerelease: false
          files: |
            build/hashes/sha256-ytm.txt
            ${{ steps.sign_ytm.outputs.signedReleaseFile0 }}
            ${{ steps.sign_ytm.outputs.signedReleaseFile1 }}
            ${{ steps.sign_ytm.outputs.signedReleaseFile2 }}
            ${{ steps.sign_ytm.outputs.signedReleaseFile3 }}
